### ISSUE TITLE
Error when running tests on earlier versions of Android and Safari mobile

### ISSUE THREAD

**Issue by Esteban26** [DevExpress/testcafe-browser-provider-browserstack#131]
Basically, I'm running my tests into browser stack and they work for most of the versions of Android and Safari mobile, but for some of them like this one:

_**erased personal data**_ testcafe "-S" "-s" "artifacts/screenshots" "-p" "${USERAGENT}\${FIXTURE}_${TEST}.png" "browserstack:Samsung Galaxy Tab 4 10.1@4.4" "test/spec/complete/A1-*.spec.ts" "--app" "node test/serve.js" "--hostname" "192.168.0.4" "--speed" "1" 

I'm getting the following error:

```{"message":"Validation Failed","errors":[{"field":"device","code":"invalid"}]}```

It seems that some browsers are not supported by testcafe or browser stack, so my question is if you have a list of the supported devices where all test cases must run; or if there is any other error I'm doing and I'm missing.

**Comment by Esteban26** [comment]
I also wrote to the BS team and they said:

_I tried to run a test against one of my own sample test suite on the device browserstack:Samsung Galaxy Tab 4 10.1@4.4.

I was able to get my test running with the below:

```npm run testcafe 'browserstack:Samsung Galaxy Tab 4 10.1@4.4' tests/```

It looks like the issue is probably being caused due to some argument that is being passed._

**Comment by wentwrong** [comment]
Personal information from your ticket (browserstack username and access key) was erased. I recommend you generate a new BrowserStack access key, because this ticket is publicly available and may have been cached before the last revision.
I confirm that the issue can be reproduced. The following error occurred during the test run:

```
ERROR Was unable to open the browser "browserstack:Samsung Galaxy Tab 4 10.1@4.4" due to error.

StatusCodeError: 422 - {"message":"Validation Failed","errors":[{"field":"device","code":"invalid"}]}
    at new StatusCodeError (/home/eax/ssss/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/home/eax/ssss/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/home/eax/ssss/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/home/eax/ssss/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at Request.<anonymous> (/home/eax/ssss/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at IncomingMessage.<anonymous> (/home/eax/ssss/node_modules/request/request.js:1076:12)
```
`Samsung Galaxy Tab 4 10.1@4.4` is present on the list of devices fetched from the BrowserStack [JS testing API endpoint](https://github.com/browserstack/api#getting-available-browsers):

```
$ testcafe -b browserstack | grep 'Samsung Galaxy Tab'
"browserstack:Samsung Galaxy Tab 2 10.1@4.0"
"browserstack:Samsung Galaxy Tab 4 10.1@4.4"
"browserstack:Samsung Galaxy Tab 4@4.4"
"browserstack:Samsung Galaxy Tab S3@7.0"
"browserstack:Samsung Galaxy Tab S3@8.0"
"browserstack:Samsung Galaxy Tab S4@8.1"
"browserstack:Samsung Galaxy Tab S5e@9.0"
"browserstack:Samsung Galaxy Tab S6@9.0"
```
I assume that BrowserStack may have forgotten to update the list returned by the API to make it stay in accordance with the list of [Browsers & Mobile Devices for JavaScript Testing](https://www.browserstack.com/list-of-browsers-and-platforms/js_testing).

**Comment by Esteban26** [comment]
Thank you for your quick reply and your advice
