### ISSUE TITLE
SyntaxError: Unexpected token B in JSON at position 0

### ISSUE THREAD

**Issue by dweber019** [DevExpress/testcafe-browser-provider-browserstack#29]
Currently I have the following issue.
When using this branch https://github.com/w3tecch/test-cafe-e2e/tree/feature/browser-stack with the command `npm run browserstack:chrome` I get this error:
```
> testcafe "browserstack:chrome@64.0:OS X High Sierra" "tests/**/*.spec.ts"

⠹
undefined:1
BrowserStackLocal v5.9
^

SyntaxError: Unexpected token B in JSON at position 0
    at JSON.parse (<anonymous>)
    at /.../test-cafe-e2e/node_modules/browserstack-local/lib/Local.js:50:23
    at ChildProcess.exithandler (child_process.js:267:7)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
```

Just fill in your credentials in `.env` after you have done `cp .env.example .env`.

**Comment by dweber019** [comment]
Could narrow it down to this error:
```
ERROR Unable to find the browser. "browserstack:Chrome@53.0:Windows 10" is not a browser alias or path to an executable file.
```

**Comment by dweber019** [comment]
Probably related to this https://github.com/browserstack/browserstack-local-nodejs/issues/31 but unsure as it has been resolved with version 1.3.0, which is the current dependency for this repo.

**Comment by AndreyBelym** [comment]
Hi @dweber019, the latest version of `browserstack-local` is [1.3.1](https://github.com/browserstack/browserstack-local-nodejs/blob/master/package.json#L3), so it must be installed as a dependency because provider specifies caret version range in the [package.json](https://github.com/DevExpress/testcafe-browser-provider-browserstack/blob/master/package.json#L33). It means that https://github.com/browserstack/browserstack-local-nodejs/issues/31 wasn't fixed, and you should open a new issue that references the old one.

**Comment by AndreyBelym** [comment]
Closing it because of issue in `browserstack-local`.
