### ISSUE TITLE
Create capabilities.name after fixture + test name or make it configurable

### ISSUE THREAD

**Issue by venth** [DevExpress/testcafe-browser-provider-browserstack#31]
Currently all tests results presented in browser stack are named accordingly to the pattern: `TestCafe test run ${id}` (e.g. result name: TestCafe test run Lf33FX1). Searching through all test results named in such a fashion for failing scenario is though thing especially if there are more than 2K tests. The correlations that might be used for finding purposes are:
- fixture name and test name or
- url to browserstack test result printed out on the console.

If the pattern would look like: `{fixture.name} {test.name}` it would ease finding a respective test scenario. Of course url to browserstack result printed out on the console would be handy as well.

**Comment by AndreyBelym** [comment]
Hi @venth, you can use the `BROWSERSTACK_PROJECT_NAME` and `BROWSERSTACK_BUILD_ID` to change project and build names of current testing session.  Fixture name or test name as a project name because there can be a number of fixtures and test in one test session.

An URL to a BrowserStack session is reported since `testcafe-browser-provider-browserstack@1.4.0`, I've just published it a moment ago. E.g. check this [test log](https://travis-ci.org/testcafe-build-bot/testcafe-browser-provider-browserstack/jobs/368585262#L2026).

**Comment by venth** [comment]
Thanks for the info about URL. I thought, I use most recent version. 
`BROWSERSTACK_PROJECT_NAME` and `BROWSERSTACK_BUILD_ID` wont do, because, as I said I have more than 2K tests to browse in one build. To ease finding, either I would use url or descriptive capabilities.name created from fixture name and test name.

**Comment by AndreyBelym** [comment]
Do you start each test in a new Browserstack session?

**Comment by venth** [comment]
Yep, we start as many as possible to parallelize them
