### ISSUE TITLE
Unable to crop the screenshot when testcafe runs on browserstack

### ISSUE THREAD

**Issue by hex0cter** [DevExpress/testcafe-browser-provider-browserstack#51]
I am not sure if this a bug in `testcafe` or `testcafe-browser-provider-browserstack`. But since it happens only when I run it again browserstack, I raise the question here.

In the test we have a `.takeElementScreenshot` for visual test. However, testcafe cannot crop the screenshot of the interested html element. Instead it take the screenshot of the whole screen (I tested chrome and iPhone on browserstack), which make the visual test useless since the time and other information on the screens are changing all the time.

## How to reproduce it?
Here is a demo project: https://github.com/hex0cter/testcafe-boilerplate

Here is part of the code in https://github.com/hex0cter/testcafe-boilerplate/blob/master/tests/test-duckduckgo-search.js:
```javascript
fixture('Test Duckduckgo search')
  .page('https://duckduckgo.com')

test('search for dogs', async (t) => {
  const searchInputField = Selector('#search_form_input_homepage')
  const searchButton = Selector('#search_button_homepage')
  const body = Selector('body')

  await t
    .expect(duckduckgo.searchInputField.exists).ok()
    .typeText(duckduckgo.searchInputField, 'dog')
    .click(duckduckgo.searchButton)
    .takeElementScreenshot(body, 'duckduckgo-screenshots.png')

  const location = await getWindowLocation();

  await t
    .expect(location.href).contains('q=dog')
})
```

Just run
``` 
yarn
yarn test:browserstack:chrome
```
or
```
yarn test:browserstack:iphone
```

Then you will see a warning like this:
```
 Warnings (1):
 --
  Was unable to take a screenshot due to an error.

  Error: Unable to locate the page area in the browser window screenshot at
  /Users/daniel.han/tmp/testcafe-boilerplate/screenshots/browserstack-chrome/duckduckgo-screenshots.png, because the page area mark with ID
  2994983835 is not found in the screenshot.
      at detectClippingArea (/Users/daniel.han/tmp/testcafe-boilerplate/node_modules/testcafe/lib/screenshots/crop.js:82:34)
      at /Users/daniel.han/tmp/testcafe-boilerplate/node_modules/testcafe/lib/screenshots/crop.js:133:30
      at Generator.next (<anonymous>)
      at step (/Users/daniel.han/tmp/testcafe-boilerplate/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /Users/daniel.han/tmp/testcafe-boilerplate/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
```

The screenshot is still captured, but not cropped to the interested html element.

**Comment by hex0cter** [comment]
![duckduckgo-screenshots](https://user-images.githubusercontent.com/9008480/45742165-a425ed80-bbf9-11e8-9bd1-8cff60d7c11b.png)
![duckduckgo-screenshots](https://user-images.githubusercontent.com/9008480/45742172-a8520b00-bbf9-11e8-9215-4002231eb5d9.png)

**Comment by rafalskalski** [comment]
Same thing is happening on my setup with testcafe 22.0  browserstack provider 1.5.1 and real mobile device browserstack.

 Warnings (1):
 --
  Was unable to take a screenshot due to an error.

  Error: Unable to locate the page area in the browser window screenshot at C:\Users\SKALR\Projects\xxx-xxx-xx-xx-xx\target\reports\2018-12-10_13-27-29\test-1\Mobile_Safari_11.0.0_iOS_11.2.0\errors\1.png, because the page area mark with ID 2406917148 is not found in the screenshot.
      at detectClippingArea (C:\Users\SKALR\Projects\sao-creditcards-ui-e2e-tests\node_modules\testcafe\src\screenshots\crop.js:61:19)
      at detectClippingArea (C:\Users\SKALR\Projects\sao-creditcards-ui-e2e-tests\node_modules\testcafe\src\screenshots\crop.js:112:26)
      at next (native)
      at step (C:\Users\SKALR\Projects\sao-creditcards-ui-e2e-tests\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
      at C:\Users\SKALR\Projects\sao-creditcards-ui-e2e-tests\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13

**Comment by mgallo** [comment]
Hi @hex0cter, the issue seems related to JS Testing API only (the default used by Testcafè). We resolved it forcing the Automate API use by setting the env variable BROWSERSTACK_USE_AUTOMATE to 1: BROWSERSTACK_USE_AUTOMATE=1 before launching the testcafè process.
testcafe v.0.23.3
testcafe-browser-provider-browserstack v.1.7.1

 Hope it helps.

**Comment by AndreyBelym** [comment]
This warning message means that TestCafe can't detect a page area in a screenshot. This happens because the Browserstack JS testing API uses a lossy image compression algorithm for screenshots, and it breaks the visual marker used by TestCafe for page area detection. You can switch to the Browserstack Automate API by setting the `BROWSERSTACK_USE_AUTOMATE` environment variable to 1 as @mgallo mentioned.
