### ISSUE TITLE
Provider is not fully compatible with the latest Firefox & geckodriver

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-browser-provider-browserstack#64]
The latest geckodriver dropped compatibility with the legacy [JsonWireProtocol](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol) WebDriver spec and its HTTP endpoints. Geckodriver now supports only endpoints described in the [W3C Web Driver](https://www.w3.org/TR/webdriver/) spec.

The provider relies on the legacy endpoints in some functionality (maximizing & resizing windows), so we need to update it to restore full compatibility with the latest Firefox from BrowserStack.

**Comment by Lukas-Kullmann** [comment]
@AndreyBelym is there any progress on this?

**Comment by AndreyBelym** [comment]
@ljowen, it should be fixed in https://github.com/DevExpress/testcafe-browser-provider-browserstack/commit/fb65abb578ed9680cccc36e8a979301181b6d85f. Please ensure that you use the latest (1.8.0) version of `testcafe-browser-provider-browserstack` and create a new issue if you can reproduce the problem with it.

@Lukas-Kullmann, it needs a fair amount of work to be done. We need to implement alternative API endpoints for Firefox.

**Comment by Lukas-Kullmann** [comment]
Thanks for the response, @AndreyBelym!

I would love to help, but I don't know how you would envision such a feature. Would you try the Web Driver endpoints and fall back to JsonWire endpoints if those are not available? Or would you do a browser switch?

By the way: I am facing the same problem as @ljowen with v1.8 and Firefox > 58. Just the error message is different (404 response since the endpoint is not available).

**Comment by Lukas-Kullmann** [comment]
For me, it seems to be working again. Tried Firefox 60 and 65 on Windows 10.

**Comment by AlexSkorkin** [comment]
Thank you for the update, @Lukas-Kullmann
