### ISSUE TITLE
By default beta version of chrome is used not latest

### ISSUE THREAD

**Issue by presha1** [DevExpress/testcafe-browser-provider-browserstack#75]
When I run my tests in browser 'browserstack:chrome', it uses beta version of chrome in Mac OS X. I want to be able to run my test in latest chrome version (whichever version it is) and not Beta version.

**Comment by Farfurix** [comment]
@presha1 

Hello,

According to the [README.md](https://github.com/DevExpress/testcafe-browser-provider-browserstack/blob/master/README.md) file, you need to specify the browser version:
```
testcafe "browserstack:Chrome@74.0" "path/to/test/file.js"
```

**Comment by presha1** [comment]
> @presha1
> 
> Hello,
> 
> According to the [README.md](https://github.com/DevExpress/testcafe-browser-provider-browserstack/blob/master/README.md) file, you need to specify the browser version:
> 
> ```
> testcafe "browserstack:Chrome@74.0" "path/to/test/file.js"
> ```

I understand that. But by default it is taking beta version, not stable. I have a config file, where I give the browser I want to run it in. And I do not want to change the browser versions everytime stable version is upgraded. So I was doing something like runner.browser('browserstack:chrome'). I need something like runner.browser('browserstack:chrome@stable:Windows 7') maybe. And do not want to upgrade chrome version everytime it is upgraded.

**Comment by Farfurix** [comment]
@presha1 

I researched it and found out that it is not BrowserStack's, but WebDriver's feature. So, we need to implement it from scratch. However, I agree that it can be useful, so I will reopen this issue as an enhancement.

**Comment by marcinlesek** [comment]
Could be really helpful! 👍

**Comment by Dvoreth** [comment]
By the way, Browserstack now offers a "latest" browser version capability :)

**Comment by arubtsov** [comment]
@Dvoreth The reporter uses [this](https://api.browserstack.com/automate/browsers.json) endpoint (it requires BrowserStack's username and access token) to get a list of available browser versions (we reverse the list and take the first version that matches given conditions - that is basically the source of the original problem). BrowserStack API output does not contain the "latest" aliases, so we need to change the endpoint and/or to implement the aliases logic in the reporter. Since using aliases is a bit different behavior than choosing the latest version by default, I created a separate [issue](https://github.com/DevExpress/testcafe-browser-provider-browserstack/issues/140) for your request.

**Comment by Obi-Dann** [comment]
I've noticed that all the browser stack beta browsers have `Beta` suffix, do you think it's possible to just filter out browsers with names containing or ending with `Beta`? the change might look something like that https://github.com/Obi-Dann/testcafe-browser-provider-browserstack/blob/a63393dce983cc4ac3b09e9a8d25355a6c88a329/src/index.js#L165

**Comment by aleks-pro** [comment]
Hello @Obi-Dann  ,

Thank you for the suggestion. It looks like it should work, but to say this for sure, we need to test it. We will take this solution into account when we start to fix the problem .

Of cource you are always welcome to create PR regarding this issue. We would appreciate this.

**Comment by AndreyBelym** [comment]
Implemented in https://github.com/DevExpress/testcafe-browser-provider-browserstack/commit/a4cc1f531aa7895a4287dd324b228c12d466d665.
