### ISSUE TITLE
How to achieve each TC test running as a new session in BS?

### ISSUE THREAD

**Issue by bennymeade** [DevExpress/testcafe-browser-provider-browserstack#76]
Hello, I will describe 2 issues here but I believe they are connected: 

I have 100 TestCafe tests running through Jenkins CI on BrowserStack.
Our BS package allows up to 10 sessions running simultaneously.

Therefore when I run my npm run command:
`"testcafe -c 6 'browserstack:chrome@74.0:OS X Mojave' tests/ -e --allow-insecure-localhost --allow-running-insecure-content --dev -r xunit:res.xml", `

I can see 6 sessions of BS firing up and running my 100 tests. But those 100 tests are shared by the 6 original sessions (approx. 16 tests per BS session). This makes finding and watching the video of failing tests very difficult. 

(# 1)
How can I get TC and BS to launch a new BS session for each of the 100 tests? And therefore tests are queued up until another BS session becomes available? 
This would allow me to find the specific test logs and video by BS session ID.

(# 2)
I'm also seeing that if I run just 1 test.only with the 'testcafe -c 6' command, BS still launches 6 sessions. 5 of which will fire up the TC proxy browser and I have to find the 1 that actually runs my test!

I imagined that command 'testcafe -c X' considered X as the maximum number of parallel tests if needed, and would only launch a new session if there was an item in the queue. This is how I experienced Selenium WedDriver / C# behaving with BrowserStack capabilities coding.

I'm using connecting method: `BROWSERSTACK_USE_AUTOMATE

I did experiment with env var BROWSERSTACK_PARALLEL_RUNS but I'm not seeing it having any impact on the number of BS sessions lunched.

Thanks in advance!

**Comment by helen-dikareva** [comment]
Hello, 
1)
Starting a new browser session for each test would be inefficient. 
You could potentially start a new session for each fixture, but again, it would be very inefficient in case if the fixtures were small (which is generally better for organizing tests).
Please take a look at a simple bash script example that demonstrates how each file from the `tests` folder is replicated in separate sessions on Browser Stack.
```sh
for file in ./tests/*
do
    ./node_modules/.bin/testcafe "browserstack:chrome@74.0:OS X Mojave" "$file"
done
```
To simplify the search for videos of failed tests, you can also use [`failedOnly` options](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/screenshots-and-videos.html#basic-video-options) for CI test running. 
2)
We considered the `only` option primarily for debugging tests. It's not expected to launch more than one browser instance because it complicates debugging.
Compilation of tests and opening browsers are heavy operations, that's why we carry them out simultaneously. So, we can not determine how many browser instances we really need to open for launched tests.

**Comment by sparda2** [comment]
Hi @helen-dikareva, we are thinking about moving to testcafe from nightwatch but we are experiencing the same issues that @bennymeade described. 

For what I have found online, it seems there is no way to actually get individual videos in Browserstack for each one of the tests I am running in parallel.  The same issue with being able to see the test name in browserstack so it's easy to debug any errors. 

My question is, in your experience with other people that are using testcafe/browserstack solution _with parallel execution_, **what is the most efficient way to find the actual failed tests and map this into the browserstack video?** 

We have a suite of 90 tests and can run up to 25 sessions in parallel in browserstack.  But every time we get some failures, it's a nightmare to try to find the video of the failed test, especially since there is no way to see the names of the tests ran on each session: 
![image](https://user-images.githubusercontent.com/16109832/65725850-de9b5380-e0b3-11e9-8d6f-0f81de37981e.png)

Ps. It would be amazing if we could set as a parameter the option of getting individual videos or videos on failure only like testcafe has for their own generated videos BUT in Browserstack. 

cc. @aariasc

**Comment by sparda2** [comment]
Sorry, and one more thing to add that makes it difficult to debug errors. The link displayed in the logs with the browserstack session that failed is wrong.  It just points to the first session in the build but not to the actual one with the failure.  
In fact, all the failures point to the same url, which is the first session in the build and this session doesn't even run the test that failed. 

In our case we ran our suite with 90 tests and 4 of them failed.  Each one of them pointed to the same BS session, but non of the failed tests were present in that video.

Not sure if this is a config issue or what but it means we have to go through each one of the videos, watch them and try to find the actual test that matches the one with the failure. 
**Any clues on what we are doing wrong here as well as my previous question?** 

![image](https://user-images.githubusercontent.com/16109832/65799207-d30f6180-e173-11e9-8098-d11cbc77f002.png)

cc. @aariasc

**Comment by aleks-pro** [comment]
Hello @sparda2 ,

_>> what is the most efficient way to find the actual failed tests and map this into the browserstack video?_
You can split your tests into groups and use separate commands to launch these groups. Set different values for the [`BROWSERSTACK_BUILD_ID`](https://github.com/DevExpress/testcafe-browser-provider-browserstack#usage) environment variable before each launch. This value will be displayed in BrowserStack.

_In our case we ran our suite with 90 tests and 4 of them failed. Each one of them pointed to the same BS session, but non of the failed tests were present in that video._ 
I have managed to reproduce the problem and created a separate [issue](https://github.com/DevExpress/testcafe/issues/4346). You can follow it to be informed of our progress.
